streamlit-> it is a free tool for deploying our machine learning projects

### Column transformers

In [18]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn
from sklearn.preprocessing import RobustScaler,StandardScaler,OneHotEncoder,OrdinalEncoder,PowerTransformer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [3]:
df=pd.read_csv(r"C:\users\saikiran\Downloads\1569614-1567135-1541251-Pandas_assignment\Pandas_assignment\Pandas_day_4\diamonds.csv")
df

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [5]:
df1=df.copy()
df1.drop(["Unnamed: 0"],axis=1,inplace=True)

In [6]:
df1

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [7]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  object
 2   color    53940 non-null  object
 3   clarity  53940 non-null  object
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   price    53940 non-null  int64
 7   x        53940 non-null  float64
 8   y        53940 non-null  float64
 9   z        53940 non-null  float64
dtypes: float64(6), int64(1), object(3)
memory usage: 4.1+ MB

In [9]:
y=df1["price"]
x=df1.drop(["price"],axis=1)

In [17]:
x.shape,y.shape

((53940, 9), (53940,))

In [21]:
from sklearn.model_selection import train_test_split as split

In [22]:
x_train,x_test,y_train,y_test=split(x,y,train_size=0.7,random_state=42)

In [25]:
print(x_train.shape,y_train.shape),
print(x_test.shape,y_test.shape)

(37758, 9) (37758,)
(16182, 9) (16182,)

In [27]:
x_train_cat=x_train.select_dtypes("object")
x_train_num=x_train.select_dtypes(include=["float64","int64"])

In [28]:
x_test_cat=x_test.select_dtypes("object")
x_test_num=x_test.select_dtypes(include=["float64","int64"])

In [44]:
ct=ColumnTransformer([
    ("continuous transformer",Pipeline([
    ("StandardScaler",StandardScaler()),
    ("Power transformer",PowerTransformer())],
    x_train_num)
])

IndentationError: unexpected indent (1210613222.py, line 3)

array([[ 1.21, 61.3 , 57.  ,  6.92,  6.87,  4.23],
       [ 0.31, 62.  , 56.  ,  4.38,  4.36,  2.71],
       [ 1.21, 62.4 , 57.  ,  6.75,  6.83,  4.24],
       ...,
       [ 0.33, 60.3 , 58.  ,  4.49,  4.46,  2.7 ],
       [ 0.9 , 62.8 , 59.  ,  6.13,  6.03,  3.82],
       [ 1.14, 60.4 , 58.  ,  6.82,  6.79,  4.11]])